# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pool:
  name: Default # your self-hosted agent pool

variables:
  buildConfiguration: "Release"
  projectPath: "$(Build.SourcesDirectory)/PersonnelInfo/PersonnelInfo.csproj"

steps:
  - task: UseDotNet@2
    displayName: "Install .NET SDK"
    inputs:
      packageType: "sdk"
      version: "8.x"

  - task: DotNetCoreCLI@2
    displayName: "Restore dependencies"
    inputs:
      command: "restore"
      projects: "$(projectPath)"
      feedsToUse: "select"

  - task: DotNetCoreCLI@2
    displayName: "Build project"
    inputs:
      command: "build"
      projects: "$(projectPath)"
      arguments: "--configuration $(buildConfiguration) --no-restore"

  - task: DotNetCoreCLI@2
    displayName: "Publish project to artifacts location"
    inputs:
      command: "publish"
      publishWebProjects: true
      arguments: "--configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)"

  - task: PublishBuildArtifacts@1
    displayName: "Upload build artifact"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"
